export const divisionList = [
  {
    id: 1,
    division: 'dhaka',
    cities: [
      'dhaka',
      'gazipur',
      'kishoreganj',
      'manikganj',
      'munshiganj',
      'narayanganj',
      'narsingdi',
      'tangail',
      'faridpur',
      'gopalganj',
      'madaripur',
      'rajbari',
      'shariatpur',
    ],
  },
  {
    id: 2,
    division: 'chittagong',
    cities: [
      'bandarban',
      'brahmanbaria',
      'chandpur',
      'chattogram',
      "cox's bazar",
      'cumilla',
      'feni',
      'khagrachhari',
      'lakshmipur',
      'noakhali',
      'rangamati',
    ],
  },
  {
    id: 3,
    division: 'khulna',
    cities: [
      'bagerhat',
      'chuadanga',
      'jashore',
      'jhenaidah',
      'khulna',
      'kushtia',
      'magura',
      'meherpur',
      'narail',
      'satkhira',
    ],
  },
  {
    id: 4,
    division: 'rajshahi',
    cities: [
      'bogura',
      'joypurhat',
      'naogaon',
      'natore',
      'chapai nawabganj',
      'pabna',
      'rajshahi',
      'sirajganj',
    ],
  },
  {
    id: 5,
    division: 'barisal',
    cities: [
      'barguna',
      'barishal',
      'bhola',
      'jhalokathi',
      'patuakhali',
      'pirojpur',
    ],
  },
  {
    id: 6,
    division: 'sylhet',
    cities: ['habiganj', 'moulvibazar', 'sunamganj', 'sylhet'],
  },
  {
    id: 7,
    division: 'rangpur',
    cities: [
      'dinajpur',
      'gaibandha',
      'kurigram',
      'lalmonirhat',
      'nilphamari',
      'panchagarh',
      'rangpur',
      'thakurgaon',
    ],
  },
];
