export const divisionList = [
  {
    id: 1,
    division: 'dhaka',
    cities: [
      'dhaka',
      'gazipur',
      'kishoreganj',
      'manikganj',
      'munshiganj',
      'narayanganj',
      'narsingdi',
      'tangail',
      'faridpur',
      'gopalganj',
      'madaripur',
      'rajbari',
      'shariatpur',
    ],
  },
  {
    id: 2,
    division: 'chittagong',
    cities: [
      'bandarban',
      'brahmanbaria',
      'chandpur',
      'chattogram',
      "cox's bazar",
      'cumilla',
      'feni',
      'khagrachhari',
      'lakshmipur',
      'noakhali',
      'rangamati',
    ],
  },
  {
    id: 3,
    division: 'khulna',
    cities: [
      'bagerhat',
      'chuadanga',
      'jashore',
      'jhenaidah',
      'khulna',
      'kushtia',
      'magura',
      'meherpur',
      'narail',
      'satkhira',
    ],
  },
  {
    id: 4,
    division: 'rajshahi',
    cities: [
      'bogura',
      'joypurhat',
      'naogaon',
      'natore',
      'chapai nawabganj',
      'pabna',
      'rajshahi',
      'sirajganj',
    ],
  },
  {
    id: 5,
    division: 'barisal',
    cities: [
      'barguna',
      'barishal',
      'bhola',
      'jhalokathi',
      'patuakhali',
      'pirojpur',
    ],
  },
  {
    id: 6,
    division: 'sylhet',
    cities: ['habiganj', 'moulvibazar', 'sunamganj', 'sylhet'],
  },
  {
    id: 7,
    division: 'rangpur',
    cities: [
      'dinajpur',
      'gaibandha',
      'kurigram',
      'lalmonirhat',
      'nilphamari',
      'panchagarh',
      'rangpur',
      'thakurgaon',
    ],
  },
];

export const address = [
  { street: 'mirpur', city: 'dhaka', division: 'dhaka', postcode: 1216 },
  { street: 'uttara', city: 'dhaka', division: 'dhaka', postcode: 1230 },
  { street: 'dhanmondi', city: 'dhaka', division: 'dhaka', postcode: 1209 },
  { street: 'banani', city: 'dhaka', division: 'dhaka', postcode: 1213 },
  { street: 'mohammadpur', city: 'dhaka', division: 'dhaka', postcode: 1207 },
  { street: 'gulshan', city: 'dhaka', division: 'dhaka', postcode: 1212 },
  { street: 'bashundhara', city: 'dhaka', division: 'dhaka', postcode: 1229 },
  { street: 'motijheel', city: 'dhaka', division: 'dhaka', postcode: 1000 },
  { street: 'farmgate', city: 'dhaka', division: 'dhaka', postcode: 1215 },
  { street: 'shantinagar', city: 'dhaka', division: 'dhaka', postcode: 1217 },
  { street: 'rajpara', city: 'rajshahi', division: 'rajshahi', postcode: 6201 },
  { street: 'motihar', city: 'rajshahi', division: 'rajshahi', postcode: 6202 },
  { street: 'boalia', city: 'rajshahi', division: 'rajshahi', postcode: 6102 },
  { street: 'shiroil', city: 'rajshahi', division: 'rajshahi', postcode: 6103 },
  { street: 'kumarpara', city: 'sylhet', division: 'sylhet', postcode: 3104 },
  { street: 'chowhatta', city: 'sylhet', division: 'sylhet', postcode: 3105 },
  { street: 'beanibazar', city: 'sylhet', division: 'sylhet', postcode: 3170 },
  { street: 'golapganj', city: 'sylhet', division: 'sylhet', postcode: 3160 },
  { street: 'fenchuganj', city: 'sylhet', division: 'sylhet', postcode: 3116 },
  { street: 'kanaighat', city: 'sylhet', division: 'sylhet', postcode: 3180 },
  { street: 'shibbari', city: 'khulna', division: 'khulna', postcode: 9000 },
  { street: 'daulatpur', city: 'khulna', division: 'khulna', postcode: 9202 },
  { street: 'boyra', city: 'khulna', division: 'khulna', postcode: 9001 },
  { street: 'rupsha', city: 'khulna', division: 'khulna', postcode: 9201 },
  { street: 'khalishpur', city: 'khulna', division: 'khulna', postcode: 9002 },
  { street: 'moylapota', city: 'khulna', division: 'khulna', postcode: 9003 },
  { street: 'batiaghata', city: 'khulna', division: 'khulna', postcode: 9260 },
];
