export const divisionList = [
  {
    id: 1,
    division: 'dhaka',
    cities: [
      'dhaka',
      'gazipur',
      'kishoreganj',
      'manikganj',
      'munshiganj',
      'narayanganj',
      'narsingdi',
      'tangail',
      'faridpur',
      'gopalganj',
      'madaripur',
      'rajbari',
      'shariatpur',
    ],
  },
  {
    id: 2,
    division: 'chittagong',
    cities: [
      'bandarban',
      'brahmanbaria',
      'chandpur',
      'chattogram',
      "cox's bazar",
      'cumilla',
      'feni',
      'khagrachhari',
      'lakshmipur',
      'noakhali',
      'rangamati',
    ],
  },
  {
    id: 3,
    division: 'khulna',
    cities: [
      'bagerhat',
      'chuadanga',
      'jashore',
      'jhenaidah',
      'khulna',
      'kushtia',
      'magura',
      'meherpur',
      'narail',
      'satkhira',
    ],
  },
  {
    id: 4,
    division: 'rajshahi',
    cities: [
      'bogura',
      'joypurhat',
      'naogaon',
      'natore',
      'chapai nawabganj',
      'pabna',
      'rajshahi',
      'sirajganj',
    ],
  },
  {
    id: 5,
    division: 'barisal',
    cities: [
      'barguna',
      'barishal',
      'bhola',
      'jhalokathi',
      'patuakhali',
      'pirojpur',
    ],
  },
  {
    id: 6,
    division: 'sylhet',
    cities: ['habiganj', 'moulvibazar', 'sunamganj', 'sylhet'],
  },
  {
    id: 7,
    division: 'rangpur',
    cities: [
      'dinajpur',
      'gaibandha',
      'kurigram',
      'lalmonirhat',
      'nilphamari',
      'panchagarh',
      'rangpur',
      'thakurgaon',
    ],
  },
];

export const address = [
  { street: 'mirpur', city: 'dhaka', division: 'dhaka', postcode: 1216 },
  { street: 'uttara', city: 'dhaka', division: 'dhaka', postcode: 1230 },
  { street: 'dhanmondi', city: 'dhaka', division: 'dhaka', postcode: 1209 },
  { street: 'banani', city: 'dhaka', division: 'dhaka', postcode: 1213 },
  { street: 'mohammadpur', city: 'dhaka', division: 'dhaka', postcode: 1207 },
  { street: 'gulshan', city: 'dhaka', division: 'dhaka', postcode: 1212 },
  { street: 'bashundhara', city: 'dhaka', division: 'dhaka', postcode: 1229 },
  { street: 'motijheel', city: 'dhaka', division: 'dhaka', postcode: 1000 },
  { street: 'farmgate', city: 'dhaka', division: 'dhaka', postcode: 1215 },
  { street: 'shantinagar', city: 'dhaka', division: 'dhaka', postcode: 1217 },

  {
    street: 'kotwali',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4000,
  },
  {
    street: 'pahartali',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4212,
  },
  {
    street: 'agrabad',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4100,
  },
  {
    street: 'halishahar',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4216,
  },
  {
    street: 'nasirabad',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4209,
  },
  {
    street: 'chawkbazar',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4215,
  },
  {
    street: 'muradpur',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4210,
  },
  {
    street: 'kaptai rastar matha',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4225,
  },
  {
    street: 'oxygen mor',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4211,
  },
  {
    street: 'hathazari',
    city: 'chittagong',
    division: 'chattogram',
    postcode: 4330,
  },

  {
    street: 'shaheb bazar',
    city: 'rajshahi',
    division: 'rajshahi',
    postcode: 6100,
  },
  {
    street: 'laxmipur',
    city: 'rajshahi',
    division: 'rajshahi',
    postcode: 6101,
  },
  { street: 'rajpara', city: 'rajshahi', division: 'rajshahi', postcode: 6201 },
  { street: 'motihar', city: 'rajshahi', division: 'rajshahi', postcode: 6202 },
  { street: 'boalia', city: 'rajshahi', division: 'rajshahi', postcode: 6102 },
  { street: 'shiroil', city: 'rajshahi', division: 'rajshahi', postcode: 6103 },
  {
    street: 'binodpur',
    city: 'rajshahi',
    division: 'rajshahi',
    postcode: 6104,
  },
  {
    street: 'naogaon sadar',
    city: 'naogaon',
    division: 'rajshahi',
    postcode: 6500,
  },
  {
    street: 'sirajganj sadar',
    city: 'sirajganj',
    division: 'rajshahi',
    postcode: 6700,
  },
  {
    street: 'pabna sadar',
    city: 'pabna',
    division: 'rajshahi',
    postcode: 6600,
  },

  { street: 'zindabazar', city: 'sylhet', division: 'sylhet', postcode: 3100 },
  { street: 'amberkhana', city: 'sylhet', division: 'sylhet', postcode: 3101 },
  { street: 'subidbazar', city: 'sylhet', division: 'sylhet', postcode: 3102 },
  {
    street: 'shahjalal upashahar',
    city: 'sylhet',
    division: 'sylhet',
    postcode: 3103,
  },
  { street: 'kumarpara', city: 'sylhet', division: 'sylhet', postcode: 3104 },
  { street: 'chowhatta', city: 'sylhet', division: 'sylhet', postcode: 3105 },
  { street: 'beanibazar', city: 'sylhet', division: 'sylhet', postcode: 3170 },
  { street: 'golapganj', city: 'sylhet', division: 'sylhet', postcode: 3160 },
  { street: 'fenchuganj', city: 'sylhet', division: 'sylhet', postcode: 3116 },
  { street: 'kanaighat', city: 'sylhet', division: 'sylhet', postcode: 3180 },

  { street: 'shibbari', city: 'khulna', division: 'khulna', postcode: 9000 },
  { street: 'daulatpur', city: 'khulna', division: 'khulna', postcode: 9202 },
  { street: 'boyra', city: 'khulna', division: 'khulna', postcode: 9001 },
  { street: 'rupsha', city: 'khulna', division: 'khulna', postcode: 9201 },
  { street: 'khalishpur', city: 'khulna', division: 'khulna', postcode: 9002 },
  { street: 'moylapota', city: 'khulna', division: 'khulna', postcode: 9003 },
  { street: 'batiaghata', city: 'khulna', division: 'khulna', postcode: 9260 },
  {
    street: 'satkhira sadar',
    city: 'satkhira',
    division: 'khulna',
    postcode: 9400,
  },
  {
    street: 'jessore sadar',
    city: 'jessore',
    division: 'khulna',
    postcode: 7400,
  },
  {
    street: 'kushtia sadar',
    city: 'kushtia',
    division: 'khulna',
    postcode: 7000,
  },

  {
    street: 'chashara',
    city: 'narayanganj',
    division: 'dhaka',
    postcode: 1420,
  },
  {
    street: 'madaripur sadar',
    city: 'madaripur',
    division: 'dhaka',
    postcode: 7900,
  },
  {
    street: 'faridpur sadar',
    city: 'faridpur',
    division: 'dhaka',
    postcode: 7800,
  },
  {
    street: 'tangail sadar',
    city: 'tangail',
    division: 'dhaka',
    postcode: 1900,
  },
  {
    street: 'gazipur chowrasta',
    city: 'gazipur',
    division: 'dhaka',
    postcode: 1702,
  },
  {
    street: 'narsingdi sadar',
    city: 'narsingdi',
    division: 'dhaka',
    postcode: 1600,
  },
  {
    street: 'manikganj sadar',
    city: 'manikganj',
    division: 'dhaka',
    postcode: 1800,
  },
  {
    street: 'munshiganj sadar',
    city: 'munshiganj',
    division: 'dhaka',
    postcode: 1500,
  },
  {
    street: 'mymensingh sadar',
    city: 'mymensingh',
    division: 'mymensingh',
    postcode: 2200,
  },
  {
    street: 'netrokona sadar',
    city: 'netrokona',
    division: 'mymensingh',
    postcode: 2400,
  },
];
